apiVersion: v1

kind: ResourceQuota

metadata:
        name: compute-quota
        namespace: dev

spec:
        hard:
                cpu: "1000"
                memory: 200Gi
                pods: "10"
