apiVersion: v1

kind: Pod

metadata:
        name: tomcat
        labels:
                name: tomcat
                type: front-end

spec:
        containers:
                - name: tomcat
                  image: tomcat
                  ports:
                          - containerPort: 8080
                  env:
                          - name: suman
                            value: "suman@123"
